#!/bin/bash

#My mac air
MPIRUN=/opt/homebrew/bin/mpirun
JULIA=/Users/simone/.juliaup/bin/julia
#TRACKALLOCATION=--track-allocation=user
TRACKALLOCATION=

#my macbook
#MPIRUN=/opt/homebrew/Cellar/open-mpi/5.0.6/bin/mpirun
#JULIA=/Applications/Julia-1.11.app/Contents/Resources/julia/bin/julia

#$MPIRUN -np $1 $JULIA --project=. -e 'include("./meshtest.jl")' "$@"
$MPIRUN -np $1 $JULIA $TRACKALLOCATION --project=. -e 'push!(empty!(ARGS), "'"$2"'", "'"$3"'"); include("./src/Jexpresso.jl")' "$@"
