#!/bin/bash
# ===========================================================================
# setup_les_run.sh -- one-shot setup for a Jexpresso LES run.
#
# Generates the mesh, orders it so the decomposition is balanced, patches the
# case's user_inputs.jl, writes a matching SLURM script, and optionally
# submits. Everything that has cost a queue cycle in practice is derived here
# rather than left to be edited by hand and kept consistent by memory:
#
#   * coarse mesh size          = fine grid / 2^REFINE_LVL
#   * rank count                = largest valid one that keeps ranks fed
#   * --nodes / --ntasks-per-node
#   * :lxy_partition / :linitial_refine / :init_refine_lvl / :gmsh_filename
#
# EDIT ONLY THE BLOCK BELOW.
# ===========================================================================

CASE="LESICP2-p4est"        # problems/CompEuler/<CASE>
GRID="32x32x30"             # FINE grid the simulation runs on (elements)
DOMAIN="10240x10240x5000"   # metres
REFINE_LVL=1                # 0 = read fine mesh directly; >=1 = p4est refinement
MAX_CORES=256               # upper bound on ranks
MEM_PER_CPU="7000M"         # per rank; setup peaks well above the time loop
SUBMIT="no"                 # "yes" to sbatch at the end

# ===========================================================================
# Nothing below here needs editing.
# ===========================================================================
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

EQS="CompEuler"
NOP=$(awk -F'=>' '/^[[:space:]]*:nop[[:space:]]*=>/ {if (match($2,/[0-9]+/)) {print substr($2,RSTART,RLENGTH); exit}}' \
      "problems/$EQS/$CASE/user_inputs.jl" 2>/dev/null || echo 4)
: "${NOP:=4}"

IFS=x read -r NX NY NZ <<< "$GRID"
IFS=x read -r LX LY LZ <<< "$DOMAIN"
CASEDIR="problems/$EQS/$CASE"
[ -d "$CASEDIR" ] || { echo "ERROR: no such case directory: $CASEDIR" >&2; exit 1; }

echo "=== 1/6  planning ==========================================="
# The planner replicates the real partitioners, so a rank count it lists is one
# the code can actually build. See tools/plan_run.jl for why the two paths have
# different rules.
eval "$(julia --project=. --startup-file=no tools/plan_run.jl \
        "$NX" "$NY" "$NZ" "$NOP" "$REFINE_LVL" "$MAX_CORES" "$LX" "$LY" --machine)"
julia --project=. --startup-file=no tools/plan_run.jl \
        "$NX" "$NY" "$NZ" "$NOP" "$REFINE_LVL" "$MAX_CORES" "$LX" "$LY"

MESHBASE="LESICP_${COARSE_NX}x${COARSE_NY}x${COARSE_NZ}_${LX}mX${LY}mX${LZ}m"
GEO="$CASEDIR/${MESHBASE}.geo"
RAW="$CASEDIR/${MESHBASE}.msh"
FINAL_MESH="$RAW"
[ "$REFINE_LVL" -gt 0 ] && FINAL_MESH="$CASEDIR/${MESHBASE}_cols.msh"

echo
echo "=== 2/6  writing $GEO ======================================="
cat > "$GEO" <<GEOEOF
// Generated by setup_les_run.sh -- do not hand-edit; re-run the script.
// ${COARSE_NX} x ${COARSE_NY} x ${COARSE_NZ} elements over ${LX} x ${LY} x ${LZ} m.
// REFINE_LVL=${REFINE_LVL} takes this to the ${NX} x ${NY} x ${NZ} grid the run uses.
nelemx = ${COARSE_NX};
nelemy = ${COARSE_NY};
nelemz = ${COARSE_NZ};

xmin = 0.0;  xmax = ${LX};
ymin = 0.0;  ymax = ${LY};
zmin = 0.0;  zmax = ${LZ};

gridsize = (xmax-xmin) / nelemx;

Point(1) = {xmin, ymin, zmin, gridsize};
Point(2) = {xmax, ymin, zmin, gridsize};
Point(3) = {xmax, ymin, zmax, gridsize};
Point(4) = {xmin, ymin, zmax, gridsize};

Line(1) = {1, 2};
Line(2) = {2, 3};
Line(3) = {3, 4};
Line(4) = {4, 1};

npx = nelemx + 1;
npz = nelemz + 1;

Transfinite Line {1, 3} = npx;
Transfinite Line {4, -2} = npz Using Progression 1.0;

Line Loop(11) = {4, 1, 2, 3};
Plane Surface(12) = {11};
Transfinite Surface {12};
Recombine Surface {12};

surfaceVector = Extrude {0,(ymax-ymin),0} {
  Surface{12};
  Layers{nelemy};
  Recombine;
};

Physical Surface("periodicy") = {12,34};
Physical Volume("internal")   = {1};
Physical Surface("top_wall")  = {33};
Physical Surface("MOST")      = {25};
Physical Surface("periodicx") = {21,29};
GEOEOF

echo "=== 3/6  gmsh ==============================================="
if ! command -v gmsh >/dev/null 2>&1; then
    echo "ERROR: gmsh not on PATH. Load it (module load gmsh) and re-run." >&2
    exit 1
fi
gmsh -3 "$GEO" -o "$RAW" -format msh2 2>/dev/null || gmsh -3 "$GEO" -o "$RAW"
echo "    wrote $RAW"

echo
echo "=== 4/6  element ordering ==================================="
if [ "$REFINE_LVL" -gt 0 ]; then
    # p4est hands each rank a CONTIGUOUS range of the mesh's element order.
    # gmsh writes horizontal layers, so without this every rank would get a
    # horizontal slab and only the ones holding the bottom layer would own any
    # ground surface -- the wall model would run on a handful of ranks.
    julia --project=. --startup-file=no tools/reorder_msh_columns.jl \
          "$RAW" "$FINAL_MESH" "$RANKS"
else
    echo "    direct path: lxy_partition bins by coordinate, so element order"
    echo "    does not matter. Skipping reorder."
fi

echo
echo "=== 5/6  patching $CASEDIR/user_inputs.jl ==================="
UI="$CASEDIR/user_inputs.jl"
[ -f "$UI.orig" ] || cp "$UI" "$UI.orig"
# Replace the value of an ACTIVE (uncommented) key. Commented-out variants are
# left alone -- these decks carry several dead :gmsh_filename lines and a blind
# sed would rewrite the wrong one.
set_key() {
    local file="$1" key="$2" val="$3"
    awk -v k=":$key" -v v="$val" '
        {
          line=$0
          if (line ~ /^[[:space:]]*#/) { print line; next }
          if (index(line, k)==0)       { print line; next }
          if (line !~ ("^[[:space:]]*" k "[[:space:]]*=>")) { print line; next }
          match(line, /^[[:space:]]*/); ind=substr(line, 1, RLENGTH)
          printf "%s%s => %s,\n", ind, k, v
          found=1; next
        }
        END { if (!found) exit 3 }
    ' "$file" > "$file.tmp" || { echo "ERROR: key :$key not found in $file" >&2; rm -f "$file.tmp"; exit 1; }
    mv "$file.tmp" "$file"
    printf '    :%-18s => %s\n' "$key" "$val"
}
set_key "$UI" gmsh_filename   "\"./$FINAL_MESH\""
set_key "$UI" linitial_refine "$([ "$REFINE_LVL" -gt 0 ] && echo true || echo false)"
set_key "$UI" init_refine_lvl "$REFINE_LVL"
set_key "$UI" lxy_partition   "$([ "$REFINE_LVL" -gt 0 ] && echo false || echo true)"

julia --project=. --startup-file=no -e "
  f=\"$UI\"; Meta.parseall(read(f,String); filename=f); println(\"    user_inputs.jl parses OK\")"

echo
echo "=== 6/6  SLURM script ======================================="
SB="submit_${CASE}.sh"
sed -e "s|^#SBATCH --nodes=.*|#SBATCH --nodes=${NODES}|" \
    -e "s|^#SBATCH --ntasks-per-node=.*|#SBATCH --ntasks-per-node=${NTASKS_PER_NODE}|" \
    -e "s|^#SBATCH --job-name=.*|#SBATCH --job-name=${CASE}|" \
    -e "s|^#SBATCH --mem-per-cpu=.*|#SBATCH --mem-per-cpu=${MEM_PER_CPU}|" \
    -e "s|^CASE=\"\${CASE:-.*|CASE=\"\${CASE:-${CASE}}\"|" \
    submit_Jexpresso_precompile_pass.sh > "$SB"
chmod +x "$SB"
echo "    wrote $SB   (nodes=${NODES}, ntasks-per-node=${NTASKS_PER_NODE}, ranks=${RANKS}, mem-per-cpu=${MEM_PER_CPU})"

cat <<SUMEOF

-----------------------------------------------------------------
 case            : $EQS / $CASE
 fine grid       : ${NX} x ${NY} x ${NZ}   (nop=${NOP})
 path            : $([ "$REFINE_LVL" -gt 0 ] && echo "p4est, ${REFINE_LVL} level(s), coarse ${COARSE_NX}x${COARSE_NY}x${COARSE_NZ}" || echo "direct read + lxy_partition")
 mesh            : $FINAL_MESH
 ranks           : ${RANKS}  (${NODES} x ${NTASKS_PER_NODE})
 gridpoints/rank : ${PTS_PER_RANK}
 ground/rank     : ${GROUND_PER_RANK}     <- must be > 0 on EVERY rank
 other valid rank counts: ${VALID_RANKS}
-----------------------------------------------------------------

Check these lines in the output when it runs:
   # Bottom faces (min/avg/max) : ${GROUND_PER_RANK} / ${GROUND_PER_RANK}.0 / ${GROUND_PER_RANK}
   # [mem] ... after ... bcast          <- should stay near baseline
SUMEOF

if [ "$SUBMIT" = "yes" ]; then
    echo; echo "submitting..."; sbatch "$SB"
else
    echo; echo "To submit:  sbatch $SB"
fi
