#---------------------------------------------------------------------------------
# Reference solution overlaid by the 1D plotter (see
# src/io/plotting/jeplots.jl): the Brio-Wu problem has no closed form, so
# the reference is a first-order finite-volume solution (HLL flux) on 10 000
# cells at t = 0.2, the same kind of reference Dao & Nazarov (2022) take
# from Athena at 10 000 points, generated by tools/brio_wu_reference.jl into
# reference_hll.dat (x ρ u v w p By Bz, 2000 samples). It is only valid at
# the final time; at other output times NaN is returned and nothing is
# drawn.
#---------------------------------------------------------------------------------
const BW_REF_FILE = joinpath(@__DIR__, "reference_hll.dat")
const BW_REF_T    = 0.2

function _bw_read_reference()
    rows = Vector{Vector{Float64}}()
    for line in eachline(BW_REF_FILE)
        (isempty(line) || startswith(line, "#")) && continue
        push!(rows, parse.(Float64, split(line)))
    end
    return reduce(hcat, rows)'   # nsamples × 8
end

function user_analytic_solution(x, t, outvar, inputs)
    npoin = length(x)
    nvar  = length(outvar)
    qref  = fill(NaN, npoin, nvar)
    abs(t - BW_REF_T) < 1.0e-6 || return qref
    isfile(BW_REF_FILE) || return qref
    tab = _bw_read_reference()
    xr  = view(tab, :, 1)
    col = Dict("ρ" => 2, "u" => 3, "v" => 4, "w" => 5, "p" => 6, "By" => 7, "Bz" => 8)
    for (ivar, name) in enumerate(outvar)
        haskey(col, string(name)) || continue
        yr = view(tab, :, col[string(name)])
        for ip = 1:npoin
            xi = clamp(x[ip], xr[1], xr[end])
            j  = clamp(searchsortedlast(xr, xi), 1, length(xr) - 1)
            θ  = (xi - xr[j])/(xr[j+1] - xr[j])
            qref[ip, ivar] = (1 - θ)*yr[j] + θ*yr[j+1]
        end
    end
    return qref
end
